all: decision_tree random_forest

decision_tree: decision_tree.c buildtree.c builtreehelper.c equation.c linklist.c traverse.c
	gcc decision_tree.c -o decision_tree -lm

random_forest: random_forest.c buildtree.c builtreehelper.c equation.c linklist.c traverse.c
	gcc random_forest.c -o random_forest -lm

 
